--------------------------------------------------------
--  파일이 생성됨 - 금요일-3월-09-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTPROFILE
--------------------------------------------------------

  CREATE TABLE "PROJECT"."CLIENTPROFILE" 
   (	"NUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"KINDS" VARCHAR2(10 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"IMAGE" VARCHAR2(50 BYTE), 
	"WRITEDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "PROJECT"."MEMBER" 
   (	"NAME" VARCHAR2(30 BYTE), 
	"USERID" VARCHAR2(30 BYTE), 
	"PWD" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"PHONE" CHAR(13 BYTE), 
	"ADMIN" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RE
--------------------------------------------------------

  CREATE TABLE "PROJECT"."RE" 
   (	"NUM" NUMBER(4,0), 
	"PASS" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"USERID" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"TITLE" VARCHAR2(40 BYTE), 
	"LANGUAGE" VARCHAR2(40 BYTE), 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"REFILE" VARCHAR2(40 BYTE), 
	"DEADLINE" DATE DEFAULT sysdate, 
	"CASH" NUMBER, 
	"READCONT" NUMBER(4,0) DEFAULT 0, 
	"WRIRDATE" DATE DEFAULT sysdate, 
	"NOW" VARCHAR2(40 BYTE) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUPPORT
--------------------------------------------------------

  CREATE TABLE "PROJECT"."SUPPORT" 
   (	"NUM" NUMBER(5,0), 
	"TITLE" VARCHAR2(50 BYTE), 
	"KINDS" VARCHAR2(50 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"PWD" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(1000 BYTE) DEFAULT NULL, 
	"ANSWERCOUNT" NUMBER(5,0) DEFAULT 0, 
	"WRITEDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSJOB
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TRANSJOB" 
   (	"JOBNUM" NUMBER, 
	"JOBCONTENT" VARCHAR2(2000 BYTE), 
	"AGENTNAME" VARCHAR2(50 BYTE), 
	"JOBREGEDATE" DATE DEFAULT sysdate, 
	"JOBTYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSPROFILE
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TRANSPROFILE" 
   (	"TRANS_NUM" NUMBER, 
	"TRANS_PICURL" VARCHAR2(50 BYTE), 
	"TRANS_SRC_LANGUAGE" VARCHAR2(20 BYTE), 
	"TRANS_AREA" VARCHAR2(40 BYTE), 
	"TRANS_PORTFOLIO" VARCHAR2(2000 BYTE), 
	"TRANS_NAME" VARCHAR2(20 BYTE), 
	"TRANS_ADDRESS" VARCHAR2(200 BYTE), 
	"TRANS_ID" VARCHAR2(30 BYTE), 
	"TRANS_PAYRATE" VARCHAR2(20 BYTE), 
	"TRANS_CONTACT" VARCHAR2(20 BYTE), 
	"TRANS_SOFTWARE" VARCHAR2(200 BYTE), 
	"TRANS_TARG_LANGUAGE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WEATHER
--------------------------------------------------------

  CREATE TABLE "PROJECT"."WEATHER" 
   (	"LOCATION" VARCHAR2(20 BYTE), 
	"TEMP" NUMBER, 
	"ICON" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence CP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJECT"."CP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRODUCT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJECT"."PRODUCT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJECT"."RE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SUPPORT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJECT"."SUPPORT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRANS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJECT"."TRANS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE ;
REM INSERTING into PROJECT.CLIENTPROFILE
SET DEFINE OFF;
Insert into PROJECT.CLIENTPROFILE (NUM,ID,NAME,KINDS,ADDRESS,IMAGE,WRITEDATE) values (2,'admin','abcabcdf','개인','aaaaaaffffff','Screenshot_12.jpg',to_date('18/02/09','RR/MM/DD'));
Insert into PROJECT.CLIENTPROFILE (NUM,ID,NAME,KINDS,ADDRESS,IMAGE,WRITEDATE) values (4,null,'ddddd','개인','aaasf','콜라보레이션3.jpg',to_date('18/02/09','RR/MM/DD'));
Insert into PROJECT.CLIENTPROFILE (NUM,ID,NAME,KINDS,ADDRESS,IMAGE,WRITEDATE) values (5,null,'ddddd','개인','aaasf','현재 git 성공1.jpg',to_date('18/02/09','RR/MM/DD'));
REM INSERTING into PROJECT.MEMBER
SET DEFINE OFF;
Insert into PROJECT.MEMBER (NAME,USERID,PWD,EMAIL,PHONE,ADMIN) values ('이소미','somi','1234','gmd@naver.com','010-2362-5157',0);
Insert into PROJECT.MEMBER (NAME,USERID,PWD,EMAIL,PHONE,ADMIN) values ('김대경','kdg88612','1234','kdg88612@naver.com','010-8606-8165',0);
Insert into PROJECT.MEMBER (NAME,USERID,PWD,EMAIL,PHONE,ADMIN) values ('김종화','kgh89209','1234','kgh89209@naver.com','010-1234-1234',0);
Insert into PROJECT.MEMBER (NAME,USERID,PWD,EMAIL,PHONE,ADMIN) values ('admin','admin','1234','admin','000-0000-0000',2);
REM INSERTING into PROJECT.RE
SET DEFINE OFF;
Insert into PROJECT.RE (NUM,PASS,NAME,USERID,EMAIL,TITLE,LANGUAGE,CONTENT,REFILE,DEADLINE,CASH,READCONT,WRIRDATE,NOW) values (4,'1234','이소미','somi','lockya@naver.com','1234','1111','ddddd',null,to_date('17/12/03','RR/MM/DD'),200000,1,to_date('18/03/09','RR/MM/DD'),'0');
Insert into PROJECT.RE (NUM,PASS,NAME,USERID,EMAIL,TITLE,LANGUAGE,CONTENT,REFILE,DEADLINE,CASH,READCONT,WRIRDATE,NOW) values (1,'1234','aaa','sss',null,'kkkk','aaaa','aaaaaaaaaaa',null,null,200000,0,to_date('18/03/09','RR/MM/DD'),'0');
Insert into PROJECT.RE (NUM,PASS,NAME,USERID,EMAIL,TITLE,LANGUAGE,CONTENT,REFILE,DEADLINE,CASH,READCONT,WRIRDATE,NOW) values (2,'1234','aaa','sss',null,'1234','aaaa','11111',null,null,200000,1,to_date('18/03/09','RR/MM/DD'),'0');
Insert into PROJECT.RE (NUM,PASS,NAME,USERID,EMAIL,TITLE,LANGUAGE,CONTENT,REFILE,DEADLINE,CASH,READCONT,WRIRDATE,NOW) values (3,'1234','aaaa','dddd',null,'ssssss','sss','123',null,to_date('18/03/31','RR/MM/DD'),200000,0,to_date('18/03/09','RR/MM/DD'),'1');
REM INSERTING into PROJECT.SUPPORT
SET DEFINE OFF;
Insert into PROJECT.SUPPORT (NUM,TITLE,KINDS,ID,PWD,EMAIL,CONTENT,ANSWERCOUNT,WRITEDATE) values (18,'aaa',null,'admin',null,null,'asdfasdfasdfasdf',0,to_date('18/02/08','RR/MM/DD'));
Insert into PROJECT.SUPPORT (NUM,TITLE,KINDS,ID,PWD,EMAIL,CONTENT,ANSWERCOUNT,WRITEDATE) values (21,'dsfasdfasdf','아이디/비밀번호찾기','admin','dfsasdf','asdfasdf','sdfasdfasf',0,to_date('18/02/09','RR/MM/DD'));
REM INSERTING into PROJECT.TRANSJOB
SET DEFINE OFF;
Insert into PROJECT.TRANSJOB (JOBNUM,JOBCONTENT,AGENTNAME,JOBREGEDATE,JOBTYPE) values (8,'hello','test',to_date('18/02/10','RR/MM/DD'),'번역');
REM INSERTING into PROJECT.TRANSPROFILE
SET DEFINE OFF;
Insert into PROJECT.TRANSPROFILE (TRANS_NUM,TRANS_PICURL,TRANS_SRC_LANGUAGE,TRANS_AREA,TRANS_PORTFOLIO,TRANS_NAME,TRANS_ADDRESS,TRANS_ID,TRANS_PAYRATE,TRANS_CONTACT,TRANS_SOFTWARE,TRANS_TARG_LANGUAGE) values (2,null,'191','ㅁㅁ','aaa','김','부산','admin','1111','010','ㅁㅁ','11');
Insert into PROJECT.TRANSPROFILE (TRANS_NUM,TRANS_PICURL,TRANS_SRC_LANGUAGE,TRANS_AREA,TRANS_PORTFOLIO,TRANS_NAME,TRANS_ADDRESS,TRANS_ID,TRANS_PAYRATE,TRANS_CONTACT,TRANS_SOFTWARE,TRANS_TARG_LANGUAGE) values (3,null,'191','ㅁㅁ','aaa','김','부산','admin','1111','010','ㅁㅁ','11');
Insert into PROJECT.TRANSPROFILE (TRANS_NUM,TRANS_PICURL,TRANS_SRC_LANGUAGE,TRANS_AREA,TRANS_PORTFOLIO,TRANS_NAME,TRANS_ADDRESS,TRANS_ID,TRANS_PAYRATE,TRANS_CONTACT,TRANS_SOFTWARE,TRANS_TARG_LANGUAGE) values (4,'Screenshot_23.jpg','194','ㅁㅁ',' ','김ss','부산','admin','1111','010','ㅁㅁ','4');
Insert into PROJECT.TRANSPROFILE (TRANS_NUM,TRANS_PICURL,TRANS_SRC_LANGUAGE,TRANS_AREA,TRANS_PORTFOLIO,TRANS_NAME,TRANS_ADDRESS,TRANS_ID,TRANS_PAYRATE,TRANS_CONTACT,TRANS_SOFTWARE,TRANS_TARG_LANGUAGE) values (5,'Screenshot_31.jpg','Arabic','ㅁㅁ',' ','김ss','부산','123456','1111','010','ㅁㅁ','Basque');
REM INSERTING into PROJECT.WEATHER
SET DEFINE OFF;
Insert into PROJECT.WEATHER (LOCATION,TEMP,ICON) values ('Daegu',6,'04d');
Insert into PROJECT.WEATHER (LOCATION,TEMP,ICON) values ('Incheon',8.02,'50d');
Insert into PROJECT.WEATHER (LOCATION,TEMP,ICON) values ('Gwangju',6,'02d');
Insert into PROJECT.WEATHER (LOCATION,TEMP,ICON) values ('Daejeon',8,'04d');
Insert into PROJECT.WEATHER (LOCATION,TEMP,ICON) values ('Ulsan',7,'04d');
Insert into PROJECT.WEATHER (LOCATION,TEMP,ICON) values ('Jeju',6,'04d');
Insert into PROJECT.WEATHER (LOCATION,TEMP,ICON) values ('Seoul',8.01,'50d');
Insert into PROJECT.WEATHER (LOCATION,TEMP,ICON) values ('Busan',7,'04d');
--------------------------------------------------------
--  DDL for Index TRANSJOB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."TRANSJOB_PK" ON "PROJECT"."TRANSJOB" ("JOBNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTPROFILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."CLIENTPROFILE_PK" ON "PROJECT"."CLIENTPROFILE" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUPPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SUPPORT_PK" ON "PROJECT"."SUPPORT" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSPROFILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."TRANSPROFILE_PK" ON "PROJECT"."TRANSPROFILE" ("TRANS_ID", "TRANS_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."MEMBER_PK" ON "PROJECT"."MEMBER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure PRINT_TABLE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PROJECT"."PRINT_TABLE" ( p_query in varchar2 )
AUTHID CURRENT_USER
is
    l_theCursor     integer default dbms_sql.open_cursor;
    l_columnValue   varchar2(4000);
    l_status        integer;
    l_descTbl       dbms_sql.desc_tab;
    l_colCnt        number;
begin
    execute immediate
    'alter session set
        nls_date_format=''yyyy-mm-dd:hh24:mi:ss'' ';
    dbms_sql.parse(  l_theCursor,  p_query, dbms_sql.native );
    dbms_sql.describe_columns
    ( l_theCursor, l_colCnt, l_descTbl );
    for i in 1 .. l_colCnt loop
        dbms_sql.define_column
        (l_theCursor, i, l_columnValue, 4000);
    end loop;
    l_status := dbms_sql.execute(l_theCursor);
    while ( dbms_sql.fetch_rows(l_theCursor) > 0 ) loop
        for i in 1 .. l_colCnt loop
            dbms_sql.column_value
            ( l_theCursor, i, l_columnValue );
            dbms_output.put_line
            ( rpad( l_descTbl(i).col_name, 30 )
              || ': ' ||
              l_columnValue );
        end loop;
        dbms_output.put_line( '-----------------' );
    end loop;
    execute immediate
        'alter session set nls_date_format=''yyyy-mm-dd'' ';
exception
    when others then
      execute immediate
          'alter session set nls_date_format=''yyyy-mm-dd'' ';
      raise;
end;

/
--------------------------------------------------------
--  Constraints for Table SUPPORT
--------------------------------------------------------

  ALTER TABLE "PROJECT"."SUPPORT" MODIFY ("NUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."SUPPORT" ADD CONSTRAINT "SUPPORT_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTPROFILE
--------------------------------------------------------

  ALTER TABLE "PROJECT"."CLIENTPROFILE" ADD CONSTRAINT "CLIENTPROFILE_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PROJECT"."CLIENTPROFILE" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSJOB
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TRANSJOB" MODIFY ("JOBNUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TRANSJOB" ADD CONSTRAINT "TRANSJOB_PK" PRIMARY KEY ("JOBNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSPROFILE
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TRANSPROFILE" MODIFY ("TRANS_PAYRATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TRANSPROFILE" MODIFY ("TRANS_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TRANSPROFILE" MODIFY ("TRANS_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TRANSPROFILE" ADD CONSTRAINT "TRANSPROFILE_PK" PRIMARY KEY ("TRANS_ID", "TRANS_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PROJECT"."TRANSPROFILE" MODIFY ("TRANS_NUM" NOT NULL ENABLE);
